# TODO: напишите production-ready Dockerfile для cmd/kvservice (см. README и задачу 10).
# Сборка из КОРНЯ репозитория:
#   docker build -f modules/09-advanced/tasks/11_project_service/Dockerfile -t kvservice .
FROM golang:1.23
